name: "test"
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
  
jobs:
  test:
    name: "test-pipeline"
    runs-on: ubuntu-latest
    steps:
    # gets AWS credentials using OpenID
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::902066978923:role/test-role-github-actions
        aws-region: ap-southeast-2
    
    - name: Copy kube-config from aws s3
      run: |
        aws s3 sync s3://kube-deploy-config configs
        
    # get k8s cluster config
    # - uses: jakejarvis/s3-sync-action@master
    #   with:
    #     args: s3://kube-deploy-config
    #   env:
    #     AWS_S3_BUCKET: kube-deploy-config
    #     AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
    #     SOURCE_DIR: './dev'      # optional: defaults to entire repository
    #     DEST_DIR: 'config'

    - name: list dev config
      run: | 
        ls configs/dev
    
    - name: get aws get-caller-identity
      run: |
        aws sts get-caller-identity

    - name: deploy to cluster
      uses: steebchen/kubectl@v2.0.0
      with: 
        config: configs/dev/sy.config.yml | base64
        command: set image --record deployment/subquery-faucet-bot-deployment --namespace subquery-apps faucet=test
    
    - name: Checkout 
      uses: actions/checkout@v2
    
