name: "test"
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
  
jobs:
  test:
    name: "test-pipeline"
    runs-on: ubuntu-latest
    steps:

    
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::902066978923:role/test-role-github-actions
        aws-region: ap-southeast-2
  
    - name: deploy to cluster
      uses: steebchen/kubectl@v2.0.0
      with: 
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        command: set image deployment/subquery-faucet-bot-deployment --namespace subquery-apps faucet=onfinality/faucet:latest
    
    - name: Checkout 
      uses: actions/checkout@v2
    
